name: .NET Core

on:
  push:
    branches: 
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Docker Build & Push
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: uzhakov/smartcom
        tag: 2.0
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
